name: low-precision-ml
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python>=3.7,<3.10
  - pip
  - numpy
  - jupyterlab
  - tqdm
  - scikit-learn
  - wandb
  - pytorch
  - torchvision
  - sphinx>=1.4
  - ipykernel
  - nbsphinx
  - tabulate
  - pip:
    - qtorch
    