# Data processing
QUANTIZE: True
PRECISION: 'FP16'
ROUNDING: ['nearest', 'stochastic']
float32: {
  'exp': 0,
  'man': 0
}
float16: {
  'exp': 6,
  'man': 9
}
float8: {
  'exp': 5,
  'man': 2
}
HYPERPARAMS: {
  'learning_rate': 0.01,
  'batch_size': 32,
  'epochs': 30
}

